// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cqrs_parttern.Domain
{
    public class Product
    {
        public string Id { get; set; }

        public string Product1 { get; set; }

        public string Price { get; set; }
    }
}

